//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GI_Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GI_Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1282897_200 {
            get {
                object obj = ResourceManager.GetObject("1282897-200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1282897_200__1_ {
            get {
                object obj = ResourceManager.GetObject("1282897-200 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1282897_200__1_1 {
            get {
                object obj = ResourceManager.GetObject("1282897-200 (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1282897_2001 {
            get {
                object obj = ResourceManager.GetObject("1282897-2001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _840131 {
            get {
                object obj = ResourceManager.GetObject("840131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _840131__1_ {
            get {
                object obj = ResourceManager.GetObject("840131 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _840131__2_ {
            get {
                object obj = ResourceManager.GetObject("840131 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap essential_compilation_icon_file_icon_document_icon_white_text_black_line_rectangle_logo_material_property_png_clipart {
            get {
                object obj = ResourceManager.GetObject("essential-compilation-icon-file-icon-document-icon-white-text-black-line-rectangl" +
                        "e-logo-material-property-png-clipart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_web_page_sales_clip_art_landing_page_design_the_emissa_group_5b8d88a8a3ced7_851213061536002216671 {
            get {
                object obj = ResourceManager.GetObject("kisspng-web-page-sales-clip-art-landing-page-design-the-emissa-group-5b8d88a8a3ce" +
                        "d7.851213061536002216671", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_web_page_sales_clip_art_landing_page_design_the_emissa_group_5b8d88a8a3ced7_851213061536002216671__2_ {
            get {
                object obj = ResourceManager.GetObject("kisspng-web-page-sales-clip-art-landing-page-design-the-emissa-group-5b8d88a8a3ce" +
                        "d7.851213061536002216671 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_web_page_sales_clip_art_landing_page_design_the_emissa_group_5b8d88a8a3ced71 {
            get {
                object obj = ResourceManager.GetObject("kisspng-web-page-sales-clip-art-landing-page-design-the-emissa-group-5b8d88a8a3ce" +
                        "d71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_web_page_sales_clip_art_landing_page_design_the_emissa_group_5b8d88a8a3ced72 {
            get {
                object obj = ResourceManager.GetObject("kisspng-web-page-sales-clip-art-landing-page-design-the-emissa-group-5b8d88a8a3ce" +
                        "d72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_web_page_sales_clip_art_landing_page_design_the_emissa_group_5b8d88a8a3ced73 {
            get {
                object obj = ResourceManager.GetObject("kisspng-web-page-sales-clip-art-landing-page-design-the-emissa-group-5b8d88a8a3ce" +
                        "d73", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_web_page_sales_clip_art_landing_page_design_the_emissa_group_5b8d88a8a3ced74 {
            get {
                object obj = ResourceManager.GetObject("kisspng-web-page-sales-clip-art-landing-page-design-the-emissa-group-5b8d88a8a3ce" +
                        "d74", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ld_white_gray {
            get {
                object obj = ResourceManager.GetObject("ld_white_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ld_white_gray1 {
            get {
                object obj = ResourceManager.GetObject("ld_white_gray1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ld_white_gray2 {
            get {
                object obj = ResourceManager.GetObject("ld_white_gray2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngfind_com_lock_icon_png_1130400 {
            get {
                object obj = ResourceManager.GetObject("pngfind.com-lock-icon-png-1130400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngfind_com_user_icon_png_168603 {
            get {
                object obj = ResourceManager.GetObject("pngfind.com-user-icon-png-168603", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pr_white_gray {
            get {
                object obj = ResourceManager.GetObject("pr_white_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pr_white_gray1 {
            get {
                object obj = ResourceManager.GetObject("pr_white_gray1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Дизайн_без_назви_page_0001 {
            get {
                object obj = ResourceManager.GetObject("Дизайн без назви_page-0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
